function convertString(words:string) {
    let separateWord = words.toLowerCase().split(' ');
    for (var i = 0; i < separateWord.length; i++) {
       separateWord[i] = separateWord[i].charAt(0).toUpperCase() +
       separateWord[i].substring(1);
    }
    return separateWord.join(' ');
}

const price = (e:any) => {
    let p
    p = e.PrecoLocacao == '' ? p :  e.PrecoLocacao
    p = e.PrecoLocacaoTemporada == '' ? p :  e.PrecoLocacaoTemporada
    p = e.PrecoVenda == '' ?  p :  e.PrecoVenda
    
    return p
}

const nego = (e:any) => {
    let p
    p = e.PrecoLocacao == '' ? p :  'Aluguel'
    p = e.PrecoLocacaoTemporada == '' ? p :  'Aluguel temporada'
    p = e.PrecoVenda == '' ?  p :  'Venda'
    
    return p
}

const exists1 = (e:any) => parseInt(e) ? e : false
const exists2 = (e:any) => e ? true : false


function array(obj:[object]) {
    const iml:[object] = obj
    const array:any = []

    iml.map((element:any) => {
        const date = new Date(element.DataCadastro)

        const w:any = {}

            w.cod = element.CodigoImovel
            w.name = element.TituloImovel || element.TipoImovel
            w.city = convertString(element.Cidade)
            w.district = convertString(element.Bairro)
            w.address = element.Endereco
            w.cep = element.CEP
            w.uf = element.UF
            w.lat = element.Latitude
            w.lon = element.Longitude
            w.c_date = date.getTime()
            w.obs = element.Observacao
            w.src = element.Fotos
            w.square = element.AreaUtil ? element.AreaUtil : element.AreaTotal
            w.price = price(element)
            w.business = nego(element)
            w.p_type = element.TipoImovel
            w.offer = element.TipoOferta
            w.condominium = exists1(element.PrecoCondominio)
            w.iptu = exists1(element.ValorIPTU)
            w.floor = exists1(element.QtdAndar)
            w.bath = exists1(element.QtdBanheiros)
            w.bedroom = exists1(element.QtdDormitorios)
            w.room = exists1(element.QtdSalas)
            w.suite = exists1(element.QtdSuites)
            w.vacancy = exists1(element.QtdVagas)
            w.garden = exists2(element.Jardim)
            w.furnished = exists2(element.Mobiliado)
            w.br_maid = exists2(element.QuartoWCEmpregada)
            w.sauna = exists2(element.Sauna)
            w.barbecue = exists2(element.Churrasqueira)
            w.intercom = exists2(element.Interfone)
            w.poll = exists2(element.Piscina)
            w.playground = exists2(element.Playground)
            w.esport = exists2(element.QuadraPoliEsportiva)
            w.party = exists2(element.SalaoFestas)
            w.games = exists2(element.SalaoJogos)
            w.whirlpool = exists2(element.SpaHidromassagem)
            w.garage = exists2(element.Garagem)

        array.push(w)
    })

    return array

}

const useJson = async () => {
        try {
            const res = await fetch("https://allmateste.com.br/xml-extract/extractXml.php", { method: 'GET' })
            const data = await res.json()

            return array(data.Imoveis.Imovel)

        } catch (error) {
            console.log("Error", error)
            return "Failed"
        }
}

export default useJson



// const Arr = [
//     {
//         address: "SRES Quadra 10 Bloco K1",
//         barbecue: false,
//         bath: false,
//         bedroom: "5",
//         br_maid: false,
//         business: "Aluguel",
//         c_date: 1503091044000,
//         cep: "70645111",
//         city: "Cruzeiro",
//         cod: "VILLA72379A01",
//         condominium: false,
//         district: "Cruzeiro Velho",
//         esport: false,
//         floor: false,
//         furnished: false,
//         games: false,
//         garage: false,
//         garden: false,
//         intercom: false,
//         iptu: false,
//         lat: "-15.7784299850464",
//         lon: "-47.9286499023438",
//         name: " LINDO E FAMILIAR ",
//         obs: "Codigo anúncio: VILLA72379 - 202104151513\nTIMA OPORTUNIDADE DE MORAR BEM NO SUDOESTE\n\nCONDOMÍNIO: 500,00\n\nO MELHOR PONTO DO SUDOESTE, PRÓXIMO:\n- SHOPPING\n- SUPERMERCADOS\n- COMÉRCIOS\n\nCONDOMÍNIO: QUALIDADE DE VIDA PERTO DE VOCÊ\n- RECÉM-CONSTRUÍDO\n- 88 m²\n- CONDOMÍNIO FECHADO\n- RESIDENCIAL\n- EXCELENTE ADMINISTRAÇÃO\n- JARDIM\n- SALÃO DE FESTAS\n- PLAYGROUND\n- ARQUITETURA MODERNA\n\nIMÓVEL: MUITO BOM GOSTO\n- COM MUITOS ARMÁRIOS NA COZINHA E NOS QUARTOS\n- BOX EM VIDRO TEMPERADO\n- 01 VAGAS DE GARAGEM\n- EXCELENTE ACABAMENTO\n- 01 SUÍTE\n- LAZER\n\nSEGURANÇA: CONFORTO E TRANQUILIDADE\n\n- ÁREA TRANQUILA DE BOA VALORIZAÇÃO NO SUDOESTE\n\n\n*****\nEsse anuncio não é real. \nSomente um teste para o site de demonstração da Allmatech",
//         offer: "2",
//         p_type: "Apartamento",
//         party: false,
//         playground: false,
//         poll: false,
//         price: "1300",
//         room: false,
//         sauna: false,
//         square: "65",
//         src: "", 
//         uf: "DF",
//         vacancy: false,
//         whirlpool: false
//     },
//     {
//         address: "Avenida Central",
//         barbecue: false,
//         bath: false,
//         bedroom: "3",
//         br_maid: false,
//         business: "Venda",
//         c_date: 1511368778000,
//         cep: "75040130",
//         city: "Anápolis",
//         cod: "VILLA80515V01",
//         condominium: false,
//         district: "Maracanã",
//         esport: false,
//         floor: false,
//         furnished: false,
//         games: false,
//         garage: false,
//         garden: false,
//         intercom: false,
//         iptu: false,
//         lat: "-16.4055004119873",
//         lon: "-48.9822006225586",
//         name: "ÓTIMA CASA EM ANÁPOLIS",
//         obs: "Codigo anúncio: VILLA80515 - 202104151513\nOPORTUNIDADE!\nEXCELENTE CASA EM ANÁPOLIS , COMPOSTA POR: \n* 3 QUARTOS (SENDO 2 SUÍTES)\n*SALA AMPLA\n*COPA\n*COZINHA COM ARMÁRIOS\n* NA LAJE\n*PISO: CERÂMICA\n*GARAGEM PARA 4 CARROS\\\nBARRACO DOS FUNDOS COMPOSTO POR:\n* 2 QUARTOS\n*WC SOCIAL\n*NA LAJE\n*PISO: CERÂMICA\n* O TERRENO POSSUI 442M² E MUITO BEM LOCALIZADA. \nLIGUE E AGENDE UMA VISITA\n\n\n\n*****\nEsse anuncio não é real. \nSomente um teste para o site de demonstração da Allmatech",
//         offer: "1",
//         p_type: "Casa",
//         party: false,
//         playground: false,
//         poll: false,
//         price: "990000",
//         room: false,
//         sauna: false,
//         square: "160",
//         src: "",
//         suite: false,
//         uf: "GO",
//         vacancy: "3",
//         whirlpool: false
//     },
//     {
//         address: "Quadra 205",
//         barbecue: true,
//         bath: "6",
//         bedroom: 1,
//         br_maid: false,
//         business: "Aluguel",
//         c_date: 1539680808000,
//         cep: "71925000",
//         city: "Aguas Claras",
//         cod: "VILLA107819A01",
//         condominium: false,
//         district: "Sul",
//         esport: true,
//         floor: false,
//         furnished: false,
//         games: true,
//         garage: false,
//         garden: false,
//         intercom: true,
//         iptu: false,
//         lat: "-15.7784299850464",
//         lon: "-47.9286499023438",
//         name: "Apartamento de Alto padrão. ",
//         obs: "Codigo anúncio: VILLA107819 - 202104151513\nApartamento com excelente planta, vazado, vista, bem dividido com área intima e área social. Piso em granito. Completo em armários planejados. \n\nÁrea Íntima: \n4 suítes amplas e com armários planejados. \n\nÁrea Social: \nSala planejada para 2 ambiente e área livre para criação de hall de entrada \nVaranda \nLavabo \nCozinha em L \nÁrea de serviço separada da cozinha \nDCE \n2 VAGAS DE GARAGEM SOLTAS \nAndar alto \n\nCondomínio: \nÁrea de lazer completa. \nChurrasqueira, Forno de pizza \nCampo de futebol, \nÁrea fitness, \nSalão gourmet, \nQuadra de futebol, quadra poliesportiva, \nSalão de festas, salão de jogos, \nSpa, \nPlayground, \nPiscina, piscina infantil, piscina aquecida, \nGuarita, segurança 24 horas e CFTV. \n\n*****\nEsse anuncio não é real. \nSomente um teste para o site de demonstração da Allmatech",
//         offer: "1",
//         p_type: "Apartamento",
//         party: true,
//         playground: true,
//         poll: true,
//         price: "5500",
//         room: false,
//         sauna: false,
//         square: "135",
//         src: "",
//         suite: false,
//         uf: "DF",
//         vacancy: "2",
//         whirlpool: true
//     },
//     {
//         address: "Rua 12",
//         barbecue: true,
//         bath: "5",
//         bedroom: "3",
//         br_maid: false,
//         business: "Venda",
//         c_date: 1539694662000,
//         cep: "72007480",
//         city: "Brasília",
//         cod: "VILLA108189V01",
//         condominium: false,
//         district: "\tsetor Habitacional Vicente Pires",
//         esport: false,
//         floor: false,
//         furnished: false,
//         games: false,
//         garage: false,
//         garden: false,
//         intercom: true,
//         iptu: false,
//         lat: "-15.794544",
//         lon: "-48.0388364",
//         name: "RUA 12 MARAVILHOSA! AC TROCA EM ÁGUAS CLARAS",
//         obs: "Codigo anúncio: VILLA108189 - 202104151513\nCasa espetacular, 2 pavimentos com projeto de iluminação\n\nAceita permuta em imóvel em Águas Claras próximo ao parque de 3 ou 4 quartos e imóvel de 1 quarto/kit.\n\nTérreo:\n\n- Living amplo com hall de entrada \n- Sala de jantar \n- Lavabo\n- Cozinha com armários \n- Cozinha de apoio\n- DCE\n- Despensa\n- Área de serviço\n\nPiso superior:\n\n- Living intimo para 2 ambientes\n- Suite 1\n- Quarto 1 com banheiro social\n- Suite master com closet,  hidromassagem e sacada\n\nÁrea de Lazer com paisagismo:\n\n- Churrasqueira\n- banheiro de apoio\n- Sauna\n- Piscina\n- Área de descanso\n- Pomar e horta\n\nCasa com todas as plantas e documentação em dia.\n\n",
//         offer: "2",
//         p_type: "Casa",
//         party: false,
//         playground: false,
//         poll: true,
//         price: "1580000",
//         room: false,
//         sauna: false,
//         square: "438",
//         src: "",
//         suite: false,
//         uf: "DF",
//         vacancy: "2",
//         whirlpool: false
//     },
//     {
//         address: "Quadra SHCGN 716",
//         barbecue: false,
//         bath: "2",
//         bedroom: "2",
//         br_maid: false,
//         business: "Venda",
//         c_date: 1539705087000,
//         cep: "70770730",
//         city: "Brasília",
//         cod: "VILLA108408V01",
//         condominium: false,
//         district: "Asa Norte",
//         esport: false,
//         floor: false,
//         furnished: false,
//         games: false,
//         garage: false,
//         garden: false,
//         intercom: false,
//         iptu: false,
//         lat: "-15.7399301528931",
//         lon: "-47.8996391296387",
//         name: "SHCGN 716 LINDO NASCENTE ELEVADOR",
//         obs: "Codigo anúncio: VILLA108408 - 202104151513\nLINDO APARTAMENTO\nTODO REFORMADO NO PORCELANATO \nARMARIOS PLANEJADOS EM TODO APARTAMENTO \nNASCENTE \nCANTO\nDCE \n\n\n*****\nEsse anuncio não é real. \nSomente um teste para o site de demonstração da Allmatech",
//         offer: "1",
//         p_type: "Apartamento",
//         party: false,
//         playground: false,
//         poll: false,
//         price: "445500",
//         room: false,
//         sauna: false,
//         square: "50",
//         src: "",
//         suite: false,
//         uf: "DF",
//         vacancy: false,
//         whirlpool: false
//     },
//     {
//         address: "Rua 4A Bloco 2",
//         barbecue: false,
//         bath: "3",
//         bedroom: "2",
//         br_maid: false,
//         business: "Aluguel",
//         c_date: 1540952132000,
//         cep: "72006206",
//         city: "Brasília",
//         cod: "VILLA111432A01",
//         condominium: false,
//         district: "\tsetor Habitacional Vicente Pires",
//         esport: false,
//         floor: false,
//         furnished: false,
//         games: false,
//         garage: false,
//         garden: false,
//         intercom: false,
//         iptu: "1500",
//         lat: "-15.64753",
//         lon: "-47.77832",
//         name: "QNL 17 BLOCO F CASA ",
//         obs: "Codigo anúncio: VILLA111432 - 202104151513\nCasa \n- Sala ampla \n- 02 Quartos com suites, 01 quarto possui banheira de hidromassagem \n- Cozinha ampla com copa \n- Banheiro social \n- Quarto de empregada \n- Dispensa \n- Jardim de inverno \n- Piscina \n- Portão eletrônico\n\n*****\nEsse anuncio não é real. \nSomente um teste para o site de demonstração da Allmatech",
//         offer: "1",
//         p_type: "Casa",
//         party: false,
//         playground: false,
//         poll: false,
//         price: "1600",
//         room: false,
//         sauna: false,
//         square: "165",
//         src: "",
//         suite: false,
//         uf: "DF",
//         vacancy: "4",
//         whirlpool: false
//     },
//     {
//         address: "Quadra QNL 17 Bloco F",
//         barbecue: false,
//         bath: "1",
//         bedroom: "1",
//         br_maid: false,
//         business: "Aluguel",
//         c_date: 1540953021000,
//         cep: "72151716",
//         city: "Taguatinga",
//         cod: "VILLA111456A01",
//         condominium: "350",
//         district: "Taguatinga Norte",
//         esport: false,
//         floor: false,
//         furnished: false,
//         games: false,
//         garage: false,
//         garden: false,
//         intercom: false,
//         iptu: "100",
//         lat: "-15.82085",
//         lon: "-48.08795",
//         name: "AV. FLAMBOYANT ED. REAL PANORAMIC,1QT, MOBILIADO ",
//         obs: "Codigo anúncio: VILLA111456 - 202104151513\n\nREAL PANORAMIC,1QT, MOBILIADO \n\nNORTE (ÁGUAS CLARAS) REAL PANORAMIC, BRASÍLIA - DF \n\nLINDO APTO 1 QTO 33,00M² MOBILIADO \nSALA MOBILIADA VISTA LIVRE. \nQUARTO MOBILIADO COMPLETO EM ÁRMÁRIOS \nBANHEIRO COM ARMARIOS E AQUECIMENTO A GÁS \nCOZINHA COM ARMÁRIOS PLANEJADOS. \n\nCONDOMÍNIO \n\nPISCINA; \nSAUNA \nESPAÇO GOURMET \nSALA DE JOGOS, \nSALÃO DE FESTAS, \nFITNESS \nLAVANDERIA \n\n\n*****\nEsse anuncio não é real. \nSomente um teste para o site de demonstração da Allmatech",
//         offer: "1",
//         p_type: "Apartamento",
//         party: false,
//         playground: false,
//         poll: false,
//         price: "1000",
//         room: false,
//         sauna: false,
//         square: "33",
//         src: "",
//         suite: false,
//         uf: "DF",
//         vacancy: "1",
//         whirlpool: false
//     },
//     {
//         address: "Quadra QRSW 8",
//         barbecue: false,
//         bath: "2",
//         bedroom: "2",
//         br_maid: false,
//         business: "Aluguel",
//         c_date: 1540962233000,
//         cep: "70675800",
//         city: "Brasília",
//         cod: "VILLA111578A01",
//         condominium: "465",
//         district: "Setor Sudoeste",
//         esport: false,
//         floor: false,
//         furnished: false,
//         games: false,
//         garage: false,
//         garden: false,
//         intercom: false,
//         iptu: "244",
//         lat: "-15.78277",
//         lon: "-47.92942",
//         name: "Apartamento",
//         obs: "Codigo anúncio: VILLA111578 - 202104151513\nSQS 307 BLOCO C \n\nExcelente Quadra na Asa Sul muito bem arborizada. \n\nApartamento Totalmente Reformado. \n\n*Armários Novos \n\n*Piso Madeira \n\n*Banheiro com Bancada e Armários \n\n*Projeto de Iluminação \n\n*Rede de Proteção em todas as Janelas \n\n*Cozinha com Bancada em Granito e armários \n\n*Área de Serviço \n\n*DCE \n\n*Gas Canalizado \n\n*Salão de Festas \n\n\n\n*****\nEsse anuncio não é real. \nSomente um teste para o site de demonstração da Allmatech",
//         offer: "1",
//         p_type: "Apartamento",
//         party: false,
//         playground: false,
//         poll: false,
//         price: "2800",
//         room: false,
//         sauna: false,
//         square: "90",
//         src: "",
//         suite: false,
//         uf: "DF",
//         vacancy: "1",
//         whirlpool: false
//     },
//     {
//         address: "Setor SMAS",
//         barbecue: false,
//         bath: "1",
//         bedroom: "1",
//         br_maid: false,
//         business: "Venda",
//         c_date: 1540968411000,
//         cep: "71215300",
//         city: "Guara",
//         cod: "VILLA111793V01",
//         condominium: false,
//         district: "Setor Industrial",
//         esport: false,
//         floor: false,
//         furnished: false,
//         games: false,
//         garage: false,
//         garden: false,
//         intercom: false,
//         iptu: false,
//         lat: "-15.7784299850464",
//         lon: "-47.9286499023438",
//         name: "SMAS Ed. Jade! 8110-4776",
//         obs: "Codigo anúncio: VILLA111793 - 202104151513\nESTUDA PROPOSTA EM TROCA DE APARTAMENTO EM ÁGUAS CLARAS!\n\n*novo\n*mobiliado\n*ótimo investimento\n\n",
//         offer: "1",
//         p_type: "Apartamento",
//         party: false,
//         playground: false,
//         poll: false,
//         price: "420000",
//         room: false,
//         sauna: false,
//         square: "40",
//         src: "",
//         suite: false,
//         uf: "DF",
//         vacancy: "1",
//         whirlpool: false
//     },
//     {
//         address: "Avenida Flamboyant",
//         barbecue: false,
//         bath: "1",
//         bedroom: "2",
//         br_maid: false,
//         business: "Aluguel",
//         c_date: 1540968603000,
//         cep: "71917000",
//         city: "Aguas Claras",
//         cod: "VILLA111800A01",
//         condominium: "415",
//         district: "Norte",
//         esport: false,
//         floor: false,
//         furnished: false,
//         games: false,
//         garage: false,
//         garden: false,
//         intercom: false,
//         iptu: "80",
//         lat: "-15.83696",
//         lon: "-48.03129",
//         name: "LINDO APTº REFORMADO!",
//         obs: "Codigo anúncio: VILLA111800 - 202104151513\nAPARTAMENTO COMPOSTO POR: \n\n*SALA \n*2 QUARTOS COM ARMÁRIOS \n*BANHEIRO SOCIAL COM ARMÁRIO \n*AR CONDICIONADO NA SALA E QUARTO \n*ARMÁRIOS EM TODOS OS AMBIENTES \n*PISO FLUTUANTE \n*APARTAMENTO DE CANTO COM VENTILAÇÃO NATURAL NO BANHEIRO \n*SALÃO DE FESTAS NO PRÉDIO \n\n\n*****\nEsse anuncio não é real. \nSomente um teste para o site de demonstração da Allmatech",
//         offer: "1",
//         p_type: "Apartamento",
//         party: false,
//         playground: false,
//         poll: false,
//         price: "2000",
//         room: false,
//         sauna: false,
//         square: "62",
//         src: "",
//         suite: false,
//         uf: "DF",
//         vacancy: false,
//         whirlpool: false
//     },
//     {
//         address: "Rua 25",
//         barbecue: false,
//         bath: "1",
//         bedroom: "1",
//         br_maid: false,
//         business: "Venda",
//         c_date: 1541631900000,
//         cep: "71927180",
//         city: "Aguas Claras",
//         cod: "VILLA112036V01",
//         condominium: "290",
//         district: "Sul",
//         esport: false,
//         floor: false,
//         furnished: false,
//         games: false,
//         garage: false,
//         garden: false,
//         intercom: false,
//         iptu: false,
//         lat: "-15.8421665378903",
//         lon: "-48.0300256288361",
//         name: "25 Sul - Piazza Praticitá ",
//         obs: "Codigo anúncio: VILLA112036 - 202104151513\n\n- 42m2 de área privativa \n- 01 Quarto \n- Armários na cozinha e WC \n- 01 WC \n- Água e gás individualizados \n- 01 vaga de garagem coberta, privativa. \n- Varanda gourmet \n- Vista panorâmica \n- Lazer completo: \n- Piscina aquecida \n- Academia \n- Salão de festas \n- Salão de jogos \n- Sauna \n- Portaria 24 horas \n- Sistema de câmeras \n\n\n*****\nEsse anuncio não é real. \nSomente um teste para o site de demonstração da Allmatech",
//         offer: "1",
//         p_type: "Apartamento",
//         party: false,
//         playground: false,
//         poll: false,
//         price: "220000",
//         room: false,
//         sauna: false,
//         square: "42",
//         src: "",
//         suite: false,
//         uf: "DF",
//         vacancy: "1",
//         whirlpool: false
//     },
//     {
//         address: "Quadra SQS 110",
//         barbecue: false,
//         bath: "3",
//         bedroom: "4",
//         br_maid: false,
//         business: "Aluguel",
//         c_date: 1542045127000,
//         cep: "70373000",
//         city: "Brasília",
//         cod: "VILLA112267A01",
//         condominium: "1860",
//         district: "Asa Sul",
//         esport: false,
//         floor: false,
//         furnished: false,
//         games: false,
//         garage: false,
//         garden: false,
//         intercom: false,
//         iptu: false,
//         lat: "-15.82004",
//         lon: "-47.90857",
//         name: "SQS 116 - Excelente Cobertura Duplex",
//         obs: "Codigo anúncio: VILLA112267 - 202104151513\nSão 290 m² bem distribuídos: \n4 quartos sendo 02 suítes com 1 Hidromassagem \n2 banheiros \n1 lavabo \nArmários em todos os cômodos \nPiso em porcelanato \nAr condicionado em todos os quartos \nCortinas \nCozinha Planejada \n2 vagas de garagem \nMODALIDADE DE GARANTIA: \n- Fiadores \n- Título de Capitalização (Brasil Cap) \n\n*****\nEsse anuncio não é real. \nSomente um teste para o site de demonstração da Allmatech",
//         offer: "1",
//         p_type: "Apartamento",
//         party: false,
//         playground: false,
//         poll: true,
//         price: "13000",
//         room: false,
//         sauna: false,
//         square: "290",
//         src: "",
//         suite: false,
//         uf: "DF",
//         vacancy: "2",
//         whirlpool: false
//     },
//     {
//         address: "Quadra CLNW 10/11",
//         barbecue: false,
//         bath: false,
//         bedroom: [],
//         br_maid: false,
//         business: "Aluguel",
//         c_date: 1542045534000,
//         cep: "70686600",
//         city: "Brasília",
//         cod: "VILLA112284A01",
//         condominium: "2305",
//         district: "Setor Noroeste",
//         esport: false,
//         floor: false,
//         furnished: false,
//         games: false,
//         garage: false,
//         garden: false,
//         intercom: false,
//         iptu: false,
//         lat: "-15.74343",
//         lon: "-47.91169",
//         name: "CLNW 10/11 BLOCO E ED. NEO 1º LOCAÇÃO ESQUINA",
//         obs: "Codigo anúncio: VILLA112284 - 202104151513\nLoja no Edifício NEO: o primeiro comércio local e a melhor oportunidade no Noroeste.\n\nLocalizada a 200 metros do Parque Burle Max, comércio pronto para receber serviços (vestuário, lavanderia, pet shop, livraria, etc), próximo também a supermercados e shopping.\n\nLoja de esquina, possui 08 vagas de garagem, pé direito duplo, mezanino, estacionamento para clientes. \nAs vagas de garagem poderão ser utilizadas como depósito/sala e o mezanino poderá ser aumentado, possibilitando a utilização de uma metragem de 240m².\n\nMODALIDADE DE GARANTIA:\n\n-FIADORES\n-TITULO DE CAPITALIZAÇÃO (BRASIL CAP)\n\n\n*****\nEsse anuncio não é real. \nSomente um teste para o site de demonstração da Allmatech",
//         offer: "1",
//         p_type: "Comercial/Industrial",
//         party: false,
//         playground: false,
//         poll: false,
//         price: "4440",
//         room: false,
//         sauna: false,
//         square: "240",
//         src: "",
//         suite: false,
//         uf: "DF",
//         vacancy: "8",
//         whirlpool: false
//     },
//     {
//         address: "SIG Quadra 1",
//         barbecue: false,
//         bath: "1",
//         bedroom: [],
//         br_maid: false,
//         business: "Aluguel",
//         c_date: 1542046314000,
//         cep: "70610410",
//         city: "Brasília",
//         cod: "VILLA112320A01",
//         condominium: "387",
//         district: "Setor De Industria Graficas",
//         esport: false,
//         floor: false,
//         furnished: false,
//         games: false,
//         garage: false,
//         garden: false,
//         intercom: false,
//         iptu: false,
//         lat: "-15.78864",
//         lon: "-47.90731",
//         name: "SHN QUADRA 01 LE QUARTIER",
//         obs: "Codigo anúncio: VILLA112320 - 202104151513\nLE QUARTIER\n\n- SALA COMERCIAL \n- AR CONDICIONADO CENTRAL\n- VISTA LIVRE\n- PRIMEIRA LOCAÇÃO\n\nMODALIDADE DE GARANTIA:\n- Fiadores\n- Título de Capitalização (Brasil Cap)\n\n\n*****\nEsse anuncio não é real. \nSomente um teste para o site de demonstração da Allmatech",
//         offer: "2",
//         p_type: "Comercial/Industrial",
//         party: false,
//         playground: false,
//         poll: false,
//         price: "1000",
//         room: false,
//         sauna: false,
//         square: "26",
//         src: "",
//         suite: false,
//         uf: "DF",
//         vacancy: "1",
//         whirlpool: false
//     },
//     {
//         address: "SIG Quadra 1",
//         barbecue: false,
//         bath: false,
//         bedroom: [],
//         br_maid: false,
//         business: "Aluguel",
//         c_date: 1542046902000,
//         cep: "70610410",
//         city: "Brasília",
//         cod: "VILLA112341A01",
//         condominium: "1100",
//         district: "Setor De Industria Graficas",
//         esport: false,
//         floor: false,
//         furnished: false,
//         games: false,
//         garage: false,
//         garden: false,
//         intercom: false,
//         iptu: false,
//         lat: "-15.7894496917725",
//         lon: "-47.908821105957",
//         name: "SIG QUADRA 1 ED. PLATINUM OFFICE 61 3039 8400",
//         obs: "Codigo anúncio: VILLA112341 - 202104151513\nLOJA COM MEZANINO!!!\n\nED. PLATINUM OFFICE\n\n\nMELHOR ENDEREÇO PARA SEU ESCRITÓRIO\nLOJA COM BANHEIRO \nVAGA PRIVATIVA\nPRÉDIO COM EXCELENTE LOCALIZAÇÃO, AO LADO DO TJDF, DE FRENTE AO   CORREIO BRAZILIENSE, FÁCIL ACESSO AO EIXO MONUMENTAL, ESPLANADA DOS MINISTÉRIOS, PRÓXIMO AO PARQUE DA CIDADE A POUCOS MINUTOS DA CÂMARA LEGISLATIVA, PALÁCIO DO BURITI. \nEDIFICO COM PORTARIA 24H, ELEVADORES.\n\n\n\n*****\nEsse anuncio não é real. \nSomente um teste para o site de demonstração da Allmatech",
//         offer: "1",
//         p_type: "Comercial/Industrial",
//         party: false,
//         playground: false,
//         poll: false,
//         price: "40000",
//         room: false,
//         sauna: false,
//         square: "97",
//         src: "",
//         suite: false,
//         uf: "DF",
//         vacancy: "1",
//         whirlpool: false
//     },
//     {
//         address: "Setor SGCV",
//         barbecue: false,
//         bath: "1",
//         bedroom: "3",
//         br_maid: false,
//         business: "Venda",
//         c_date: 1542047584000,
//         cep: "71215100",
//         city: "Guara",
//         cod: "VILLA112372V01",
//         condominium: false,
//         district: "Setor Industrial",
//         esport: false,
//         floor: false,
//         furnished: false,
//         games: false,
//         garage: false,
//         garden: false,
//         intercom: true,
//         iptu: false,
//         lat: "-15.82292",
//         lon: "-47.95356",
//         name: "ÓTIMO APARTAMENTO ",
//         obs: "Codigo anúncio: VILLA112372 - 202104151513\n-VAZADO\n-TRÊS QUARTOS\n-SALA DOIS AMBIENTES\n-COZINHA\n\n\n*****\nEsse anuncio não é real. \nSomente um teste para o site de demonstração da Allmatech\n",
//         offer: "1",
//         p_type: "Apartamento",
//         party: false,
//         playground: false,
//         poll: false,
//         price: "1000000",
//         room: false,
//         sauna: false,
//         square: "63",
//         src: "",
//         suite: false,
//         uf: "DF",
//         vacancy: false,
//         whirlpool: false
//     },
//     {
//         address: "Quadra CLN 307",
//         barbecue: false,
//         bath: "1",
//         bedroom: "1",
//         br_maid: false,
//         business: "Venda",
//         c_date: 1542047604000,
//         cep: "70746500",
//         city: "Brasília",
//         cod: "VILLA112373V01",
//         condominium: false,
//         district: "Asa Norte",
//         esport: false,
//         floor: false,
//         furnished: false,
//         games: false,
//         garage: false,
//         garden: false,
//         intercom: true,
//         iptu: false,
//         lat: "-15.76844",
//         lon: "-47.88632",
//         name: "QMSW 05 OPORTUNIDADE",
//         obs: "Codigo anúncio: VILLA112373 - 202104151513\nLINDA KIT;\n\n-DIVIDIDA;\n-ARMÁRIOS;\n-EXCELENTE LOCALIZAÇÃO;\n-VISTA LIVRE;\n-NASCENTE;\n\n\n\n*****\nEsse anuncio não é real. \nSomente um teste para o site de demonstração da Allmatech",
//         offer: "1",
//         p_type: "Apartamento",
//         party: false,
//         playground: false,
//         poll: false,
//         price: "280000",
//         room: false,
//         sauna: false,
//         square: "25",
//         src: "",
//         suite: false,
//         uf: "DF",
//         vacancy: "1",
//         whirlpool: false
//     },
//     {
//         address: "Setor SGCV",
//         barbecue: false,
//         bath: false,
//         bedroom: [],
//         br_maid: false,
//         business: "Aluguel",
//         c_date: 1542047622000,
//         cep: "71215100",
//         city: "Guara",
//         cod: "VILLA112374A01",
//         condominium: false,
//         district: "Setor Industrial",
//         esport: false,
//         floor: false,
//         furnished: false,
//         games: false,
//         garage: false,
//         garden: false,
//         intercom: false,
//         iptu: false,
//         lat: "-15.82292",
//         lon: "-47.95356",
//         name: "SAAN QUADRA 3 - DE 690 AO FIM - LADO PAR ÓTIMA OPORTUNIDADE!",
//         obs: "Codigo anúncio: VILLA112374 - 202104151513\nÓTIMA OPORTUNIDADE!\n\nPrédio comercial, constituído por 5 pavimentos; \n\n- 2º e 3º subsolos: Áreas destinadas a estacionamento, com pintura e numeração de vagas e faixas de segurança. \n- 1º subsolo: Destinado á escritório composto de 04 unidades autônomas \n\n- Pavimento térreo: Hall de entrada principal e duas unidades autônomas \n- Pavimento Superior- Circulação, hall de elevadores e duas unidades autônomas Esquadrias em alumínio anodizado e vidros escuros. Dois elevadores (ala norte e sul), cada um deles com capacidade para 8 passageiros, escadaria em concreto armado, revestido em granito polido. Instalação de ar condicionado central que distribui o fluxo de ar, por meio de 15 \\\"fancoils\\\" distribuídos no primeiro subsolo, térreo e pavimento superior. O prédio também conta com sistema completo de instalação anti-incêndio, instalações completas de rede elétrica. Espaço bem planejado e amplo, ideal para empresas na área central de Brasília. \n\n\n*****\nEsse anuncio não é real. \nSomente um teste para o site de demonstração da Allmatech",
//         offer: "1",
//         p_type: "Comercial/Industrial",
//         party: false,
//         playground: false,
//         poll: false,
//         price: "100",
//         room: false,
//         sauna: false,
//         square: "1784",
//         src: "",e: false,
//         uf: "DF",
//         vacancy: false,
//         whirlpool: false
//     },
//     {
//         address: "Quadra QMSW 5",
//         barbecue: false,
//         bath: false,
//         bedroom: [],
//         br_maid: false,
//         business: "Venda",
//         c_date: 1542048178000,
//         cep: "70680500",
//         city: "Brasília",
//         cod: "VILLA112376V01",
//         condominium: false,
//         district: "Setor Sudoeste",
//         esport: false,
//         floor: false,
//         furnished: false,
//         games: false,
//         garage: false,
//         garden: false,
//         intercom: false,
//         iptu: false,
//         lat: "-15.79557",
//         lon: "-47.91989",
//         name: "Terreno Vicente Pires - 300m2",
//         obs: "Codigo anúncio: VILLA112376 - 202104151513\nFEROLA, vencedora do prêmio Colibri pelo 7o ano consecutivo, a mais acessada em Brasília, vende: \nLote Vicente Pires \n- Otimamente bem localizado (Próximo de Supermercados, comércio local, ponto de ônibus, etc.) \n- Acesso rápido à EPTG \n- 300m2 \n- Murado \n- Condomínio fechado \n- Guarita \n- Aceita troca por apartamento em Águas Claras",
//         offer: "1",
//         p_type: "Terreno",
//         party: false,
//         playground: false,
//         poll: false,
//         price: "280000",
//         room: false,
//         sauna: false,
//         square: "300",
//         src: "",
//         suite: false,
//         uf: "DF",
//         vacancy: "10",
//         whirlpool: false
//     },
//     {
//         address: "Rua 36",
//         barbecue: true,
//         bath: "3",
//         bedroom: "1",
//         br_maid: false,
//         business: "Venda",
//         c_date: 1542048361000,
//         cep: "71919180",
//         city: "Aguas Claras",
//         cod: "VILLA112382V01",
//         condominium: "800",
//         district: "Norte",
//         esport: true,
//         floor: false,
//         furnished: false,
//         games: true,
//         garage: false,
//         garden: false,
//         intercom: true,
//         iptu: false,
//         lat: "-15.89819",
//         lon: "-47.77159",
//         name: "Quadra 205 - Águas Claras",
//         obs: "Codigo anúncio: VILLA112382 - 202104151513\nApartamento Quadra 205 \n\n- Apartamento na melhor quadra de Águas Claras, próximo ao Shopping. \n- Originalmente de 4 quartos transformado em 3 quartos, podendo reverter novamente; \n- 97m2 de área útil \n- DCE \n- Armários planejados em todos os cômodos \n- 02 vagas descobertas. \n- Lazer completo (piscina, sauna, churrasqueira, salão de festas, etc.) \n\nSomos correspondente bancário Caixa - aprovamos seu financiamento com agilidade. \n\nAgende sua visita \n\n*****\nEsse anuncio não é real. \nSomente um teste para o site de demonstração da Allmatech",
//         offer: "2",
//         p_type: "Apartamento",
//         party: true,
//         playground: true,
//         poll: false,
//         price: "500000",
//         room: "1",
//         sauna: false,
//         square: "97",
//         src: "",
//         suite: false,
//         uf: "DF",
//         vacancy: "2",
//         whirlpool: true
//     },
//     {
//         address: "Quadra CA 6",
//         barbecue: false,
//         bath: "2",
//         bedroom: "2",
//         br_maid: false,
//         business: "Venda",
//         c_date: 1542048393000,
//         cep: "71503506",
//         city: "Brasília",
//         cod: "VILLA112383V01",
//         condominium: "350",
//         district: "Lago Norte",
//         esport: false,
//         floor: false,
//         furnished: false,
//         games: true,
//         garage: false,
//         garden: false,
//         intercom: true,
//         iptu: false,
//         lat: "-15.80884",
//         lon: "-48.03128",
//         name: "Wave - Rua 18 norte - Águas Claras ",
//         obs: "Codigo anúncio: VILLA112383 - 202104151513\nWave Residence \n- 67m2 de área útil \n- 2 Quartos \n- Armários na cozinha e banheiros \n- 01 vaga no subsolo \n- Varanda grande \n- Lazer completo: \n- Piscina coberta aquecida \n- Sala de jogos \n- Academia \n- Spa \n- Espaço Gourmet \n- Portaria 24 horas \n- Sistema de câmeras \n- Próximo à estação Central do metrô \n- Próximo ao Parque \n\n\n*****\nEsse anuncio não é real. \nSomente um teste para o site de demonstração da Allmatech",
//         offer: "1",
//         p_type: "Apartamento",
//         party: true,
//         playground: true,
//         poll: false,
//         price: "50000",
//         room: false,
//         sauna: false,
//         square: "67",
//         src: "",
//         suite: false,
//         uf: "DF",
//         vacancy: "1",
//         whirlpool: true
//     },
//     {
//         address: "Rua 3",
//         barbecue: false,
//         bath: "4",
//         bedroom: "2",
//         br_maid: true,
//         business: "Venda",
//         c_date: 1544191277000,
//         cep: "71907360",
//         city: "Aguas Claras",
//         cod: "VILLA113359V01",
//         condominium: "1",
//         district: "Norte",
//         esport: false,
//         floor: "1",
//         furnished: true,
//         games: false,
//         garage: false,
//         garden: true,
//         intercom: false,
//         iptu: "1",
//         lat: "-15.7784299850464",
//         lon: "-47.9286499023438",
//         name: "excelente casa para familia",
//         obs: "Codigo anúncio: VILLA113359 - 202104151513\nApartamento com excelente planta, vazado, vista, bem dividido com área intima e área social. Piso em granito. Completo em armários planejados. \n\nÁrea Íntima: \n4 suítes amplas e com armários planejados. \n\nÁrea Social: \nSala planejada para 2 ambiente e área livre para criação de hall de entrada \nVaranda \nLavabo \nCozinha em L \nÁrea de serviço separada da cozinha \nDCE \n2 VAGAS DE GARAGEM SOLTAS \nAndar alto \n\nCondomínio: \nÁrea de lazer completa. \nChurrasqueira, Forno de pizza \nCampo de futebol, \nÁrea fitness, \nSalão gourmet, \nQuadra de futebol, quadra poliesportiva, \nSalão de festas, salão de jogos, \nSpa, \nPlayground, \nPiscina, piscina infantil, piscina aquecida, \nGuarita, segurança 24 horas e CFTV. \n\n\n*****\nEsse anuncio não é real. \nSomente um teste para o site de demonstração da Allmatech",
//         offer: "2",
//         p_type: "Casa",
//         party: false,
//         playground: false,
//         poll: false,
//         price: "58000",
//         room: "1",
//         sauna: true,
//         square: "1",
//         src: "",
//         suite: "2",
//         uf: "DF",
//         vacancy: "2",
//         whirlpool: false
//     }
    
// ]



// export default Arr







